name = "learning"
version = "0.1.0"
defaultTargets = ["learning"]
lintDriver = "batteries/runLinter"
testDriver = "learning_test"

[[require]]
name = "batteries"
scope = "leanprover-community"

[[lean_lib]]
name = "Learning"

[[lean_lib]]
name = "Test"

[[lean_exe]]
name = "learning"
root = "Main"

[[lean_exe]]
name = "learning_test"
root = "Test"
