name = "learning"
version = "0.1.0"
defaultTargets = ["learning", "Learning"]
lintDriver = "batteries/runLinter"
testDriver = "learning_test"

[[lean_lib]]
name = "Learning"
globs = ["Learning.+"]

[[lean_lib]]
name = "Test"

[[lean_exe]]
name = "learning"
root = "Learning"

[[lean_exe]]
name = "learning_test"
root = "Test"

[[require]]
name = "batteries"
scope = "leanprover-community"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.31.0"  # matches toolchain version

